{{- if eq .Values.controller.kind "deployment" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.controller.name | trunc 63 }}
  labels:
    app: {{ .Values.controller.name | trunc 63 }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.controller.name | trunc 63 }}
  template:
    metadata:
      labels:
        app: {{ .Values.controller.name | trunc 63 }}
{{- if .Values.prometheus }}
{{- if and (.Values.controller.nginxplus)  (.Values.prometheus.create) }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.prometheus.port }}"
{{- end }}
{{- end }}
    spec:
{{- if .Values.controller.serviceAccountName }}
      serviceAccountName: {{ .Values.controller.serviceAccountName }}
{{- end }}
      hostNetwork: {{ .Values.controller.hostNetwork }}
      containers:
      - image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
        name: {{ .Values.controller.name | trunc 63 }}
        imagePullPolicy: "{{ .Values.controller.image.pullPolicy }}"
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
{{- if .Values.controller.nginxplus }}
          - -nginx-plus
{{- end }}
          - -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
{{- if .Values.controller.defaultTLS.secret }}
          - -default-server-tls-secret={{ .Values.controller.defaultTLS.secret }}
{{ else }}
          - -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret
{{- end }}
{{- if .Values.controller.ingressClass }}
          - -ingress-class={{ .Values.controller.ingressClass }}
{{- end }}
{{- if .Values.controller.useIngressClassOnly }}
          - -use-ingress-class-only={{ .Values.controller.useIngressClassOnly }}
{{- end }}
{{- if .Values.controller.watchNamespace }}
          - -watch-namespace={{ .Values.controller.watchNamespace }}
{{- end }}
{{- if .Values.controller.healthStatus }}
          - -health-status
{{- end }}
{{- if .Values.prometheus }}
{{- if and (.Values.controller.nginxplus)  (.Values.prometheus.create) }}
      - image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
        name: nginx-prometheus-exporter
        imagePullPolicy: "{{ .Values.prometheus.image.pullPolicy }}"
        ports:
        - name: prometheus
          containerPort: {{ .Values.prometheus.port }}
        args:
          - -web.listen-address
          - :{{ .Values.prometheus.port }}
          - -nginx.plus
          - -nginx.scrape-uri
          - http://127.0.0.1:8080/api
{{- end }}
{{- end }}
{{- end }}
